### ISSUE TITLE
"rediscovered"?

### ISSUE THREAD

**Issue by gingerbeardman** [nickgravgaard/qwerty-flip#4]
Hi Nick,

The QWERTY-Flip website says you "rediscovered" it, but makes no mention of the original. Can you let me know who came up with it before you?

Cheers!
matt

**Comment by nick-gravgaard** [comment]
I don't have a timeline of who else came up with the same layout, but I have found some names people have used for it. On the QWERTY-Flip website I wrote:

>This has been discovered independently over and over again (and often given unimaginative names like QWDFGY, ASERT, or ASERTH)

So I would search for those and see what you can find. Good luck!
